antonspro/about/urls.py
from django.conf.urls import url
from . import views


app_name='about'

urlpatterns= [
    url(r'aboutSu$',views.SuAbout.as_view(),name='aboutsu'),
    url(r'^general/$',views.GenAbout.as_view(),name='general'),
    url(r'^planet/$',views.PlanetAbout.as_view(),name='aboutpe')
]

antonspro/antonspro/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Home/$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^$',views.MasterPage.as_view(),name='masterpage'),
    url(r'^sudoku/',include('sudoku.urls',namespace='sudoku')),
    url(r'^about/',include('about.urls',namespace='about')),
]

antonspro/about/models.py
from django.db import models

# Create your models here.

antonspro/about/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class GenAbout(TemplateView):
    template_name= 'about/generalabout.html'

class SuAbout(TemplateView):
    template_name= 'about/aboutsudoku.html'

class PlanetAbout(TemplateView):
    template_name= 'about/planetabout.html'

antonspro/about/templates/about/aboutsudoku.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'antonspro/css/about.css' %}">
    <script src="http://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id="bignav">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'masterpage' %}" id="homenav"></a>
        <a href="{% url 'about:general' %}" class="navbar-brand mynav">About</a>
        <ul class="nav navbar-nav navbar-right">

        </ul>
      </div>
    </nav>

    <div class="list-group" id="sidenav">
      <a href="{% url 'about:general' %}"><button type="button" class="list-group-item">General</button></a>
      <a href="{% url 'about:aboutpe' %}"><button type="button" class="list-group-item">Planet Express app</button></a>
      <a href="{% url 'about:aboutsu' %}"><button type="button" class="list-group-item"id="GeneralB">Sudoku puzzle solver</button></a>
    </div>

  <div class="" id="textbox">

  </div>








    <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
    </script>
  </body>
</html>

antonspro/about/templates/about/generalabout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'antonspro/css/about.css' %}">
    <script src="http://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id="bignav">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'masterpage' %}" id="homenav"></a>
        <a href="{% url 'about:general' %}" class="navbar-brand mynav">About</a>
        <ul class="nav navbar-nav navbar-right">

        </ul>
      </div>
    </nav>

  <div class="list-group" id="sidenav">
    <a href="{% url 'about:general' %}"><button type="button" class="list-group-item" id="GeneralB">General</button></a>
    <a href="{% url 'about:aboutpe' %}"><button type="button" class="list-group-item">Planet Express app</button></a>
    <a href="{% url 'about:aboutsu' %}"><button type="button" class="list-group-item">Sudoku puzzle solver</button></a>
  </div>

  <div class="" id="textbox">

  </div>








    <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
    </script>
  </body>
</html>

antonspro/about/templates/about/planetabout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'antonspro/css/about.css' %}">
    <script src="http://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id="bignav">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'masterpage' %}" id="homenav"></a>
        <a href="{% url 'about:general' %}" class="navbar-brand mynav">About</a>
        <ul class="nav navbar-nav navbar-right">

        </ul>
      </div>
    </nav>

    <div class="list-group" id="sidenav">
      <a href="{% url 'about:general' %}"><button type="button" class="list-group-item">General</button></a>
      <a href="{% url 'about:aboutpe' %}"><button type="button" class="list-group-item" id="GeneralB">Planet Express app</button></a>
      <a href="{% url 'about:aboutsu' %}"><button type="button" class="list-group-item">Sudoku puzzle solver</button></a>
    </div>

  <div class="" id="textbox">

  </div>








    <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
    </script>
  </body>
</html>